[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "whisper-subtitles"
version = "0.5.0"
authors = [
    {name = "brendan-jarvis"},
]
description = "Generate subtitles for audio/video files in a directory using OpenAI's Whisper"
readme = "README.md"
requires-python = ">=3.8"
keywords = ["subtitles", "openai", "whisper"]
license = {text = "LICENSE"}


dynamic = ["dependencies"]

[tool.setuptools.dynamic]
dependencies = {file = ["requirements.txt"]}

[project.urls]
"Homepage" = "https://github.com/brendan-jarvis/WhisperSubtitles"
"Bug Tracker" = "https://github.com/brendan-jarvis/WhisperSubtitles/issues"


[project.scripts]
whisper-subtitles = "whisper_subtitles:cli"